### ISSUE TITLE
Container execution in browser?

### ISSUE THREAD

**Issue by burgreen** [vsoch/sifweb#3]
Is it possible that a Singularity container can be executed within a browser? 

Since Go was compiled to WASM, can the WASM Go be used to execute Singularity on a container? Or, can Singularity itself be compiled to WASM and then be used to execute a container?

**Comment by vsoch** [comment]
Thanks for the question! At least at the time of creating this, there wasn't enough emulation of an actual filesystem that WASM could support to enable this (I remember trying it). Wasm has changed / developed fairly quickly so you could definitely give another look! Notably, the code here just treats the container as a binary, and then reads information from the header, which is a very different goal than running the container binary. I remember at the time reading about [this](https://browsix.org/) and my intuition was that Singularity would need some custom build to remove expectations of different mounts, etc. Anyway, it's definitely something you could look into and pursue! Please report back if you make any progress.
